name: hello-world

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Hello World
        run: echo Hello world
